"""empty message

Revision ID: 155cd4f31384
Revises: 5eb1b85e321f
Create Date: 2021-06-17 12:37:46.185063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155cd4f31384'
down_revision = '5eb1b85e321f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iptofingerprint', sa.Column('hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iptofingerprint', 'hash')
    # ### end Alembic commands ###
