"""empty message

Revision ID: 5eb1b85e321f
Revises: 
Create Date: 2021-06-17 12:35:11.130186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb1b85e321f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookietofingerprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipaddress', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('useragenthttp', sa.String(), nullable=True),
    sa.Column('accept', sa.String(), nullable=True),
    sa.Column('accept_encoding', sa.String(), nullable=True),
    sa.Column('accept_language', sa.String(), nullable=True),
    sa.Column('dnt', sa.String(), nullable=True),
    sa.Column('adblocker', sa.String(), nullable=True),
    sa.Column('cookies', sa.String(), nullable=True),
    sa.Column('languagesjs', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('plugins', sa.String(), nullable=True),
    sa.Column('screenwidth', sa.String(), nullable=True),
    sa.Column('screenheight', sa.String(), nullable=True),
    sa.Column('screendepth', sa.String(), nullable=True),
    sa.Column('storagelocal', sa.String(), nullable=True),
    sa.Column('storagesession', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('useragentjs', sa.String(), nullable=True),
    sa.Column('mimetypes', sa.String(), nullable=True),
    sa.Column('webGLvendor', sa.String(), nullable=True),
    sa.Column('webGLrenderer', sa.String(), nullable=True),
    sa.Column('fonts', sa.String(), nullable=True),
    sa.Column('canvasprint', sa.String(), nullable=True),
    sa.Column('audiofingerprint', sa.String(), nullable=True),
    sa.Column('cookie_id', sa.String(), nullable=True),
    sa.Column('request_header', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iptofingerprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipaddress', sa.String(), nullable=True),
    sa.Column('useragenthttp', sa.String(), nullable=True),
    sa.Column('accept', sa.String(), nullable=True),
    sa.Column('accept_encoding', sa.String(), nullable=True),
    sa.Column('accept_language', sa.String(), nullable=True),
    sa.Column('dnt', sa.String(), nullable=True),
    sa.Column('adblocker', sa.String(), nullable=True),
    sa.Column('cookies', sa.String(), nullable=True),
    sa.Column('languagesjs', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('plugins', sa.String(), nullable=True),
    sa.Column('screenwidth', sa.String(), nullable=True),
    sa.Column('screenheight', sa.String(), nullable=True),
    sa.Column('screendepth', sa.String(), nullable=True),
    sa.Column('storagelocal', sa.String(), nullable=True),
    sa.Column('storagesession', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('useragentjs', sa.String(), nullable=True),
    sa.Column('mimetypes', sa.String(), nullable=True),
    sa.Column('webGLvendor', sa.String(), nullable=True),
    sa.Column('webGLrenderer', sa.String(), nullable=True),
    sa.Column('fonts', sa.String(), nullable=True),
    sa.Column('canvasprint', sa.String(), nullable=True),
    sa.Column('audiofingerprint', sa.String(), nullable=True),
    sa.Column('cookie_id', sa.String(), nullable=True),
    sa.Column('request_header', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iptofingerprint')
    op.drop_table('cookietofingerprint')
    # ### end Alembic commands ###
